### ISSUE TITLE
net.bungie.HCE.yml Throwing errors when trying to build the flatpak

### ISSUE THREAD

**Issue by EpicMinerBackupOfficial** [Akusesu/Halo-1#1]
Do I need too make these folders my self? or what it is slightly confusing

**Comment by EpicMinerBackupOfficial** [comment]
Correction I I uderstand how to set it up now but now the real issue I'm having this error I tried converting the yml too a json but that didn't work
`` jeffry@jeffry-MS-7693:~/.var/app/net.bungie.HCE$ flatpak-builder --force-clean builds net.bungie.HCE.yml --install
Can't parse 'net.bungie.HCE.yml': <data>:1:6: Parse error: unexpected identifier `app-id', expected value
 ``

**Comment by refi64** [comment]
What errors exactly?

**Comment by lionirdeadman** [comment]
I actually think I know what your issue might be..

Have you followed the [instructions to get flatpak up and running on Ubuntu](https://flatpak.org/setup/Ubuntu/)?

This would then cause the flatpak-builder to think it is JSON instead of YML therefore the manifest failing to be read. So please follow these instructions and tell us if it works afterwards, thanks!

(Sorry for only seeing this now)

**Comment by lionirdeadman** [comment]
Closing since you've not given any new information, re-open if need be.

**Comment by refi64** [comment]
@lionirdeadman You forgot to actually hit close...
